apiVersion: kdeps.io/v1
kind: Resource

metadata:
  actionId: speak
  name: Speak Response
  requires:
    - respond

run:
  tts:
    text: "{{ get('respond') }}"
    mode: offline
    offline:
      engine: espeak
