apiVersion: kdeps.io/v1
kind: Resource

metadata:
  actionId: faqResponse
  name: FAQ API Response
  requires:
    - briefAnswer
    - detailedAnswer

run:
  apiResponse:
    success: true
    response:
      data:
        question: get('q')
        brief:    get('briefAnswer')
        detailed: get('detailedAnswer')
    meta:
      headers:
        Content-Type: application/json
