apiVersion: kdeps.io/v1
kind: Resource

metadata:
  actionId: callResponse
  name: Call Response
  requires:
    - ttsResponse

run:
  restrictToHttpMethods: [POST]
  restrictToRoutes: [/api/v1/call]
  apiResponse:
    success: true
    response:
      transcript: "{{ inputTranscript }}"
      answer: "{{ get('llmResponse') }}"
      audio: "{{ ttsOutput() }}"
