version: 2
before:
  hooks:
    - go mod tidy
builds:
  - id: kdeps-darwin
    binary: kdeps
    ldflags:
      - -s -w -X main.version={{ .Env.VERSION }} -X main.commit={{ .Env.COMMIT_SHA }}
    main: ./
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
    env:
      - CC=o64-clang
      - CXX=o64-clang++
      - CGO_ENABLED=1
    flags:
      - -trimpath

  - id: kdeps-linux-amd64
    binary: kdeps
    main: ./
    env:
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
      - CGO_ENABLED=1
    goarch:
      - amd64
    goos:
      - linux
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{ .Env.VERSION }} -X main.commit={{ .Env.COMMIT_SHA }}
  - id: kdeps-linux-arm64
    binary: kdeps
    main: ./
    goarch:
      - arm64
    goos:
      - linux
    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
      - CGO_ENABLED=1
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{ .Env.VERSION }} -X main.commit={{ .Env.COMMIT_SHA }}
  - id: kdeps-windows-amd64
    binary: kdeps
    main: ./
    goarch:
      - amd64
    goos:
      - windows
    env:
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
      - CGO_ENABLED=1
    ldflags:
      - -s -w -X main.version={{ .Env.VERSION }} -X main.commit={{ .Env.COMMIT_SHA }}
    flags:
      - -trimpath
      - -buildmode=exe

release:
  make_latest: false
  prerelease: true

archives:
  - format: tar.gz
    builds:
      - kdeps-linux-arm64
      - kdeps-linux-amd64
      - kdeps-darwin
      - kdeps-windows-amd64
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# .goreleaser.yaml
brews:
  - name: kdeps

    # Git author used to commit to the repository.
    commit_author:
      name: jjuliano
      email: joelbryan.julianoe@gmail.com

    # Folder inside the repository to put the formula.
    directory: Formula

    # The project name and current git tag are used in the format string.
    #
    # Templates: allowed
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"

    # Your app's homepage.
    homepage: "https://kdeps.com"
    description: "Kdeps is a framework for creating dockerized AI Agent APIs"

    dependencies:
      - name: git

    repository:
      owner: kdeps
      name: homebrew-tap

nfpms:
  - package_name: kdeps
    homepage: https://kdeps.com
    maintainer: Joel Bryan Juliano <joelbryan.juliano@gmail.com>
    description: "Kdeps is a framework for creating dockerized AI Agent APIs"
    vendor: Kdeps
    license: Apache-2.0 license
    formats:
      - apk
      - deb
    dependencies:
      - git
