apiVersion: kdeps.io/v1
kind: Workflow

metadata:
  name: telephony-bot
  description: AI phone call handler using Twilio + Deepgram STT + LLM + OpenAI TTS
  version: "1.0.0"
  targetActionId: callResponse

settings:
  apiServerMode: true
  hostIp: "0.0.0.0"
  portNum: 16395

  apiServer:
    routes:
      - path: /api/v1/call
        methods: [POST]
    cors:
      enableCors: true
      allowOrigins:
        - "*"

  agentSettings:
    timezone: Etc/UTC
    pythonVersion: "3.12"
    installOllama: true
    models:
      - llama3.2:1b

  input:
    sources: [telephony]
    telephony:
      type: online
      provider: twilio
    transcriber:
      mode: online
      output: text
      language: en-US
      online:
        provider: deepgram
        apiKey: "YOUR_DEEPGRAM_API_KEY"   # Replace or set DEEPGRAM_API_KEY env var
