apiVersion: kdeps.io/v1
kind: Workflow

metadata:
  name: file-upload
  description: File upload handling example with multipart form-data
  version: "1.0.0"
  targetActionId: fileProcessor

settings:
  apiServerMode: true
  hostIp: "0.0.0.0"
  portNum: 16395

  apiServer:
    routes:
      - path: /api/v1/upload
        methods: [POST]
    cors:
      enableCors: true
      allowOrigins:
        - "*"

  agentSettings:
    timezone: Etc/UTC
    pythonVersion: "3.12"
