apiVersion: kdeps.io/v1
kind: Resource
metadata:
  actionId: finalResponse
  name: Final Response
  requires:
    - sayHello
run:
  apiResponse:
    success: true
    response:
      message: "{{ get('greeting') }}"
