apiVersion: kdeps.io/v1
kind: Resource

metadata:
  actionId: batchUpdate
  name: Batch User Updates

run:
  restrictToHttpMethods: [POST]
  restrictToRoutes: [/api/v1/sql-demo]

  sql:
    connectionName: analytics
    transaction: true
    queries:
      - query: |
          UPDATE users
          SET status = $1,
              updated_at = NOW()
          WHERE id = $2
        paramsBatch: "{{ get('user_updates') }}"
