apiVersion: kdeps.io/v1
kind: Resource

metadata:
  actionId: results
  name: Combined Results
  requires: [analytics, batchUpdate]

run:
  apiResponse:
    success: true
    response:
      analytics: "{{ get('analytics') }}"
      batch_results: "{{ get('batchUpdate') }}"
      timestamp: "{{ info('current_time') }}"
