apiVersion: kdeps.io/v1
kind: Resource
metadata:
  actionId: response
  requires: [indexDoc, searchDocs]
run:
  apiResponse:
    success: true
    response:
      results: "{{ output('searchDocs').results }}"
      count: "{{ output('searchDocs').count }}"
