apiVersion: kdeps.io/v1
kind: Workflow

metadata:
  name: auth-base
  description: Base workflow providing shared authentication logic.
  version: "1.0.0"
  targetActionId: authCheck

settings:
  apiServerMode: false # not intended to run standalone
