apiVersion: kdeps.io/v1
kind: Resource

metadata:
  actionId: collectInputs
  name: Collect Inputs via Built-in Input Component

run:
  component:
    name: input
    with:
      query: "What is the capital of France?"
      text: "The Eiffel Tower is in Paris."
      key: "location"
