apiVersion: kdeps.io/v1
kind: Resource

metadata:
  actionId: answer
  name: Answer the Query
  requires:
    - collectInputs

run:
  chat:
    model: llama3.2:latest
    prompt: |
      Context: {{ output('collectInputs') | json_decode | get('text') }}

      Question: {{ output('collectInputs') | json_decode | get('query') }}

      Answer the question concisely based on the provided context.
