apiVersion: kdeps.io/v1
kind: Resource

metadata:
  actionId: response
  name: Final Response
  requires:
    - answer

run:
  apiResponse:
    success: true
    response:
      inputs: "{{ output('collectInputs') }}"
      answer: "{{ get('answer') }}"
