apiVersion: kdeps.io/v1
kind: Resource

metadata:
  actionId: chat
  name: AI Chat
  requires:
    - authCheck # This resource comes from the @auth-base import!

run:
  chat:
    model: llama3.2:1b
    role: user
    prompt: "{{ get('message') }}"
    scenario:
      - role: system
        prompt: "You are a helpful AI assistant. Answer concisely."
    timeoutDuration: 60s
