apiVersion: kdeps.io/v1
kind: Resource

metadata:
  actionId: markdownTool
  name: Markdown Renderer Tool

run:
  component:
    name: markdown-renderer
    with:
      text: "{{ get('text', 'memory') }}"
      output_format: "{{ get('output_format', 'memory') }}"
