apiVersion: kdeps.io/v1
kind: Resource

metadata:
  actionId: csvTool
  name: CSV Analyzer Tool

run:
  component:
    name: csv-analyzer
    with:
      data: "{{ get('data', 'memory') }}"
      table_format: "{{ get('table_format', 'memory') }}"
      max_rows: "{{ get('max_rows', 'memory') }}"
