apiVersion: kdeps.io/v1
kind: Workflow

metadata:
  name: mustache-expressions-demo
  description: Demonstrates mustache-style expressions alongside expr-lang
  version: "1.0.0"
  targetActionId: response

settings:
  apiServerMode: true
  hostIp: "0.0.0.0"
  portNum: 16395

  apiServer:
    routes:
      - path: /api/demo
        methods: [GET, POST]
    cors:
      enableCors: true
      allowOrigins:
        - "*"

  agentSettings:
    timezone: Etc/UTC
