apiVersion: kdeps.io/v1
kind: Workflow

metadata:
  name: shell-exec
  description: Shell command execution examples
  version: "1.0.0"
  targetActionId: finalResult

settings:

  apiServer:
    portNum: 16395
    routes:
      - path: /api/v1/exec
        methods: [GET, POST]
    cors:
      enableCors: true
      allowOrigins:
        - "*"

  agentSettings:
    timezone: Etc/UTC
