apiVersion: kdeps.io/v1
kind: Workflow

metadata:
  name: shell-exec
  description: Shell command execution examples
  version: "1.0.0"
  targetActionId: finalResult

settings:
  apiServerMode: true
  hostIp: "0.0.0.0"
  portNum: 16395

  apiServer:
    routes:
      - path: /api/v1/exec
        methods: [GET, POST]
    cors:
      enableCors: true
      allowOrigins:
        - "*"

  agentSettings:
    timezone: Etc/UTC
