apiVersion: kdeps.io/v1
kind: Resource

metadata:
  actionId: response
  name: Final Response
  requires:
    - summarize

run:
  apiResponse:
    success: true
    response:
      file: "{{ input('filePath') }}"
      analysis: "{{ get('summarize') }}"
