apiVersion: kdeps.io/v1
kind: Resource

metadata:
  actionId: response
  name: Final Response
  requires:
    - countIntro
    - countPoem

run:
  apiResponse:
    success: true
    response:
      intro_stats: "{{ output('countIntro') }}"
      poem_stats:  "{{ output('countPoem') }}"
