apiVersion: kdeps.io/v1
kind: Workflow

metadata:
  name: vision
  description: Vision model example with image upload and analysis
  version: "1.0.0"
  targetActionId: visionResponse

settings:
  apiServerMode: true
  hostIp: "0.0.0.0"
  portNum: 16395

  apiServer:
    routes:
      - path: /api/v1/vision
        methods: [POST]
    cors:
      enableCors: true
      allowOrigins:
        - "*"

  agentSettings:
    timezone: Etc/UTC
    pythonVersion: "3.12"
    installOllama: true
    models:
      - moondream:1.8b
      - llava:7b
