apiVersion: kdeps.io/v1
kind: Workflow

metadata:
  name: chatbot
  description: Simple LLM chatbot
  version: "1.0.0"
  targetActionId: responseResource

settings:
  apiServerMode: true
  hostIp: "0.0.0.0"
  portNum: 3000

  apiServer:
    routes:
      - path: /api/v1/chat
        methods: [POST]
    cors:
      enableCors: true
      allowOrigins:
        - "*"

  agentSettings:
    timezone: Etc/UTC
    pythonVersion: "3.12"
    installOllama: true
    models:
      - llama3.2:1b
