apiVersion: kdeps.io/v1
kind: Component
metadata:
  name: formatter
  description: Formatting utilities
  version: "1.0.0"
resources:
  - actionId: formatName
    name: Format Name Resource
    after:
      - set('formattedName', get('name'))
  - actionId: addTimestamp
    name: Timestamp Resource
    after:
      - set('timestamp', now())
