name: Test installer script

on:
  push:
    branches: [ main ]
    paths:
      - 'install.sh'
  pull_request:
    branches: [ main ]
    paths:
      - 'install.sh'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-install-unix:
    runs-on: ubuntu-latest
    steps:
      - name: Use install script
        run: curl -LsSf https://raw.githubusercontent.com/kdeps/kdeps/${{ github.sha }}/install.sh | sh -s -- -d
      - name: Run kdeps version
        run: kdeps


  test-install-windows:
    runs-on: windows-latest
    steps:
      - name: Use install script
        shell: bash
        run: curl -LsSf https://raw.githubusercontent.com/kdeps/kdeps/${{ github.sha }}/install.sh | sh -s -- -d
      - name: Run kdeps version
        shell: bash
        run: /c/Users/runneradmin/.local/bin/kdeps.exe
